### ISSUE TITLE
Timetable times change when DST/NON DST

### ISSUE THREAD

**Issue by mkaufmann** [harald-lang/tutor#35]

**Comment by mkaufmann** [comment]
See application.rb config.time_zone

**Comment by kordianbruck** [comment]
Enabled the setting, so that everything is saved to DB in UTC. Active record automatically retrieves/saves records in the correct timezone, once this setting is activated.

We might have to replace some `Time.parse` calls, but I couldn't find any, at first glance.

More info here: https://www.varvet.com/blog/working-with-time-zones-in-ruby-on-rails/

**Important**
(This might be problematic, with already existing data, as it most probably is not saved in UTC. You'll have to convert it manually once bevor updating to the newest version)
