### ISSUE TITLE
CSV data import

### ISSUE THREAD

**Issue by harald-lang** [harald-lang/tutor#55]
For the upcoming winter term, we need a new feature that allows us to import students/groups from the matching system.

**Comment by kimiya66** [comment]
Dear Harald,


I am working on a task which Linnea assigned to me (solving a problem in controllers which relates to Passwords-controller.rb file) as soon as I finish this I will start the task you assigned to me (reading students data from matching system).

I am really apologize that I am slow in these weeks because of exams. it would be until mid of this month and after that I will spend more time for work and compensate this.


Thank you and best,

Kimia

________________________________

**Comment by harald-lang** [comment]
Dear Kimia,

no worries, we have plenty of time for that. We plan to import the data on 22.10.2017.

best,
Harald

**Comment by kimiya66** [comment]
Dear Harald,


Thanks a lot for your understanding.


Regards,


________________________________

**Comment by harald-lang** [comment]
Der Kimiya,

I decided to do the import manually.
Therefore, I will close this issue. Iff, everything works well with the matching (and we continue to use it), I will reopen that issue.

Kind regards,
HL
